#!/bin/bash/

. ./check_empty_space

function create_files {

file_name=""
index_to_repeat_file=0
name_with_ex=$(basename -- "$file_names")
extension="${name_with_ex##*.}"
name_without_ex="${name_with_ex%.*}"
name_without_ex_length=${#name_without_ex}
max_repetitions=235
num_files=$(( $RANDOM % 3 + 1 ))
created_files=0
counter_to_repeat_file=0

free_space=$(check_empty_space)

for dir in $(find $path -type d -name '*231122*'); do
	echo $dir
	while [[ $free_space == "Enough free space" ]] && [ $created_files -le $num_files ]; do
		file_name=$(generate_filename)
		file_name+="_"
		file_name+=$(date +"%d%m%y")
		fallocate -l $file_size"MB" $dir/$file_name"."$extension
		((++created_files))
		echo "File created: $(pwd $dir)/$file_name"."$extension - $(date +"%d-%m-%Y") - $(du -h $dir/$file_name"."$extension | awk '{print $1}')" >> log_file.log
		if [[ $counter_to_repeat -lt $max_repetitions ]]; then
			((++counter_to_repeat_file))
		else
			counter_to_repeat_file=0
			((++index_to_repeat_file))
		fi
		free_space=$(check_empty_space)
	done
done

}


function generate_filename {

#	echo "Inside generate filename"

	file_name_g_f=""

	for (( letter_index=0; letter_index<$name_without_ex_length; ++letter_index ))
	do
		last_char_g_f="${file_name: -1}"
		current_char_g_f="${name_without_ex: letter_index:1}"
		if [[ $last_char != $current_char ]]
		then
			file_name_g_f+=$current_char_g_f;
		fi

		if [[ $letter_index -eq index_to_repeat ]]
		then
			for (( repeat_index=0; repeat_index<counter_to_repeat_file; ++repeat_index))
			do
			file_name_g_f+=$current_char_g_f;
			done
		fi
	done

	file_name_g_f_len=${#file_name_g_f}
	last_char_file_name_g_f="${file_name_g_f: -1}"
	while [ $file_name_g_f_len -lt 5 ]
	do
		file_name_g_f+=$last_char_file_name_g_f;
		((++file_name_g_f_len))
	done

	echo $file_name_g_f

}

