variables:
  TELEGRAM_BOT_TOKEN: "YOUR_BOT_TOKEN"
  TELEGRAM_USER_ID: "YOUR_USER_ID"

stages:
  - build
  - style-check
  - test
  - ci_notify_success
  - ci_notify_failure
  - deploy
  - cd_notify_success
  - cd_notify_failure

build:
  stage: build
  tags:
    - ws1_cicd
  script:
    - cd src/C3_SimpleBashUtils-0/src/cat/
    - make
    - cd ..
    - cd grep/
    - make
  artifacts:
    paths:
    - src/C3_SimpleBashUtils-0/src/cat/s21_cat
    - src/C3_SimpleBashUtils-0/src/grep/s21_grep
    expire_in: 30 days

style-check:
  stage: style-check
  tags:
    - ws1_cicd
  script:
    - cd src/C3_SimpleBashUtils-0/src/
    - clang-format -n cat/s21_cat.c &>> clang_output.txt
    - clang-format -n cat/s21_cat.h &>> clang_output.txt
    - clang-format -n cat/test_cat.sh &>> clang_output.txt
    - clang-format -n grep/s21_grep.c &>> clang_output.txt
    - clang-format -n grep/s21_grep.h &>> clang_output.txt
    - clang-format -n grep/test_grep.sh &>> clang_output.txt
    - clang-format -n grep/old_test_grep.sh &>> clang_output.txt
    # Uncomment to fail the CI stage
    #- clang-format -n grep/Makefile &>> clang_output.txt
    - bash pipeline_scripts/check_clang_output.sh
    - cat clang_output.txt
  allow_failure: false

test:
  stage: test
  tags:
    - ws1_cicd
  script:
    - cd src/C3_SimpleBashUtils-0/src/cat/
    - make test_cat
    - cd ..
    - cd grep/
    - make test_grep
    - bash ../pipeline_scripts/check_test_results.sh
  allow_failure: false

ci_notify_success:
  stage: ci_notify_success
  tags:
    - ws1_cicd
  script:
  - bash src/06/ci_notify.sh ✅

ci_notify_failure:
  stage: ci_notify_failure
  tags:
    - ws1_cicd
  script:
  - bash src/06/ci_notify.sh ❌
  when: on_failure

deploy:
  stage: deploy
  when: manual
  tags:
    - ws1_cicd
  script:
    - bash src/C3_SimpleBashUtils-0/src/pipeline_scripts/copy_files_to_ws2.sh
    # Uncomment to fail the CD stage
    #- bash src/C3_SimpleBashUtils-0/src/pipeline_scripts/doesnt_exist.sh
  allow_failure: false

cd_notify_success:
  stage: cd_notify_success
  tags:
    - ws1_cicd
  script:
  - bash src/06/cd_notify.sh ✅

cd_notify_failure:
  stage: cd_notify_failure
  tags:
    - ws1_cicd
  script:
  - bash src/06/cd_notify.sh ❌
  when: on_failure
