/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_strcmp_test.check" instead.
 */

#include <check.h>

#line 1 "s21_strcmp_test.check"
#include <string.h>
#include "../s21_string.h"

START_TEST(s21_strcmp_test1)
{
#line 5
    const char *input1 = "Hello, I am your new coach.";
    const char *input2 = "Hello, I am your new coach.";
    ck_assert_int_eq(s21_strcmp(input1, input2), strcmp(input1, input2));

}
END_TEST

START_TEST(s21_strcmp_test2)
{
#line 10
    const char *input1 = "Hello, I am your new coach. Hey";
    const char *input2 = "Hello, I am your new coach.";
    ck_assert_int_eq(s21_strcmp(input1, input2), strcmp(input1, input2));

}
END_TEST

START_TEST(s21_strcmp_test3)
{
#line 15
    const char *input1 = "Hello, I am your new coach?";
    const char *input2 = "Hello, I am your new coach.";
    ck_assert_int_eq(s21_strcmp(input1, input2), strcmp(input1, input2));

}
END_TEST

START_TEST(s21_strcmp_test4)
{
#line 20
    const char *input1 = "Hello, I am your new coach.";
    const char *input2 = "Hello, I am your new coach?";
    ck_assert_int_eq(s21_strcmp(input1, input2), strcmp(input1, input2));

}
END_TEST

START_TEST(s21_strcmp_test5)
{
#line 25
    const char *input1 = "Hello, I am your new coach.";
    const char *input2 = "Hello, I am your new coach.";
    ck_assert_int_eq(s21_strcmp(input1, input2), strcmp(input1, input2));

}
END_TEST

START_TEST(s21_strcmp_test6)
{
#line 30
    const char *input1 = "Hello, I am your new coach!!";
    const char *input2 = "Hello, I am your new coach??";
    ck_assert_int_eq(s21_strcmp(input1, input2), strcmp(input1, input2));

}
END_TEST

START_TEST(s21_strcmp_test7)
{
#line 35
    const char *input1 = "";
    const char *input2 = "Hello, I am your new coach??";
    ck_assert_int_eq(s21_strcmp(input1, input2), strcmp(input1, input2));

}
END_TEST

START_TEST(s21_strcmp_test8)
{
#line 40
    const char *input1 = "Hello, I am your new coach!!";
    const char *input2 = "";
    ck_assert_int_eq(s21_strcmp(input1, input2), strcmp(input1, input2));

}
END_TEST

START_TEST(s21_strcmp_test9)
{
#line 45
    const char *input1 = "";
    const char *input2 = "";
    ck_assert_int_eq(s21_strcmp(input1, input2), strcmp(input1, input2));

}
END_TEST

START_TEST(s21_strcmp_test10)
{
#line 50
    const char *input1 = "wow";
    const char *input2 = "";
    ck_assert_int_eq(s21_strcmp(input1, input2), strcmp(input1, input2));

}
END_TEST

START_TEST(s21_strcmp_test11)
{
#line 55
    const char *input1 = "";
    const char *input2 = "WOW!";
    ck_assert_int_eq(s21_strcmp(input1, input2), strcmp(input1, input2));

}
END_TEST

START_TEST(s21_strcmp_test12)
{
#line 60
    const char *input1 = "!@#4567\0456";
    const char *input2 = "!\0";
    ck_assert_int_eq(s21_strcmp(input1, input2), strcmp(input1, input2));

}
END_TEST

START_TEST(s21_strcmp_test13)
{
#line 65
    const char *input1 = "!@#4567\0456";
    const char *input2 = "!@#4567\0456";
    ck_assert_int_eq(s21_strcmp(input1, input2), strcmp(input1, input2));

}
END_TEST

START_TEST(s21_strcmp_test14)
{
#line 70
    const char *input1 = "That was fucking amazing!";
    const char *input2 = "Exactly!";
    ck_assert_int_eq(s21_strcmp(input1, input2), strcmp(input1, input2));

}
END_TEST

START_TEST(s21_strcmp_test15)
{
#line 75
    const char *input1 = "Exactly!";
    const char *input2 = "That was fucking amazing!";
    ck_assert_int_eq(s21_strcmp(input1, input2), strcmp(input1, input2));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_strcmp_test1);
    tcase_add_test(tc1_1, s21_strcmp_test2);
    tcase_add_test(tc1_1, s21_strcmp_test3);
    tcase_add_test(tc1_1, s21_strcmp_test4);
    tcase_add_test(tc1_1, s21_strcmp_test5);
    tcase_add_test(tc1_1, s21_strcmp_test6);
    tcase_add_test(tc1_1, s21_strcmp_test7);
    tcase_add_test(tc1_1, s21_strcmp_test8);
    tcase_add_test(tc1_1, s21_strcmp_test9);
    tcase_add_test(tc1_1, s21_strcmp_test10);
    tcase_add_test(tc1_1, s21_strcmp_test11);
    tcase_add_test(tc1_1, s21_strcmp_test12);
    tcase_add_test(tc1_1, s21_strcmp_test13);
    tcase_add_test(tc1_1, s21_strcmp_test14);
    tcase_add_test(tc1_1, s21_strcmp_test15);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
