#!/bin/bash/

function check_input {

# Check the num of variables
num_arv=6
if [ $# -ne $num_arv ]
then
	echo "There should be only 6 parameters. No more, no less"
	# 7 - Argument list is too long code
	exit 7
fi

# Check if the dir exists
dir=$1
if [ ! -d "$dir" ]
then
	echo "Directory doesn't exist. Please enter a valid directory"
	# 2 - No such file or directory
	exit 2
fi

# Check if the number of folders is really a number
# TODO: should also think about 0 folders case later
number_of_folders=$2
if [[ "${number_of_folders}" =~ [^0-9] ]]
then
	echo "Number of folders should be only a number"
	exit 1
fi

# Check the number of chars for folders
max_char_folder_name=7
len_folder_name=${#3}
if [ $len_folder_name -gt $max_char_folder_name ]
then
	echo "Folder name shouldn't be greater than 7 chars"
	# 36 - File name too long
	exit 36
fi

# Check if the folder name is only letters
folder_name=$3
if [[ "${folder_name}" =~ [^a-zA-Z] ]]
then
	echo "Folder name should contain only letters"
	exit 1
fi

# Check the number of files
num_files=$4
if [ $num_files -eq 0 ]
then
	echo "There should be more than 0 files"
	exit 1
fi
if [[ "${num_files}" =~ [^0-9] ]]
then
	echo "Value should only be a number"
fi


# Check the filename
filename_and_ext=$5
strings=$(echo $filename_and_ext | tr "." "\n")
filename=${strings[0]}
ext=${strings[1]}
echo "$filename"
echo "$ext"
last_string_len=${#strings[2]}
echo "$last_string_len"
if [ ! -z "$strings[2]" ]
then
	echo "There should be only one dot"
	exit 1
fi


}
