/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_memmove_test.check" instead.
 */

#include <check.h>

#line 1 "s21_memmove_test.check"
#include <string.h>
#include "../s21_string.h"

START_TEST(s21_memmove_test1)
{
#line 5
    const char *source = "Hello, I am your new coach. Surprised?";
    
    char s21_destination[100];
    memset(s21_destination, 0, 100);
    char destination[100];
    memset(destination, 0, 100);
    
    const s21_size_t size = s21_strlen(source);

    char *s21_destination_copy = s21_memmove(s21_destination, source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);


}
END_TEST

START_TEST(s21_memmove_test2)
{
#line 22
    const char *source = "Hello, I am your new coach. Surprised? Stunned?";
    
    char s21_destination[100];
    memset(s21_destination, 0, 100);
    char destination[100];
    memset(destination, 0, 100);
    
    const s21_size_t size = s21_strlen(source);

    char *s21_destination_copy = s21_memmove(s21_destination, source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);


}
END_TEST

START_TEST(s21_memmove_test3)
{
#line 39
    const char *source = "Hello, I am your new coach. Surprised? Stunned?";
    
    char s21_destination[100];
    memset(s21_destination, 0, 100);
    char destination[100];
    memset(destination, 0, 100);
    
    const s21_size_t size = s21_strlen(source) / 2;

    char *s21_destination_copy = s21_memmove(s21_destination, source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);


}
END_TEST

START_TEST(s21_memmove_test4)
{
#line 56
    const char *source = "";
    
    char s21_destination[100];
    memset(s21_destination, 0, 100);
    char destination[100];
    memset(destination, 0, 100);
    
    const s21_size_t size = s21_strlen(source);

    char *s21_destination_copy = s21_memmove(s21_destination, source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);


}
END_TEST

START_TEST(s21_memmove_test5)
{
#line 73
    const char *source = "Wow";
    
    char s21_destination[100];
    memset(s21_destination, 0, 100);
    char destination[100];
    memset(destination, 0, 100);
    
    const s21_size_t size = s21_strlen(source);

    char *s21_destination_copy = s21_memmove(s21_destination, source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);


}
END_TEST

START_TEST(s21_memmove_test6)
{
#line 90
    const char *source = "Wow";
    
    char s21_destination[100];
    memset(s21_destination, 0, 100);
    char destination[100];
    memset(destination, 0, 100);
    
    const s21_size_t size = 0;

    char *s21_destination_copy = s21_memmove(s21_destination, source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);


// TESTS WITH OVERLAPPING SOURCE AND DESTINATION

}
END_TEST

START_TEST(s21_memmove_test7)
{
#line 109
    char s21_source[] = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};
    char source[] = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};
    
    char *s21_destination = s21_source + 2;    
    char *destination = source + 2;
    
    const s21_size_t size = 5;

    char *s21_destination_copy = s21_memmove(s21_destination, s21_source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);


}
END_TEST

START_TEST(s21_memmove_test8)
{
#line 125
    char s21_source[] = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};
    char source[] = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};
    
    char *s21_destination = s21_source + 3;    
    char *destination = source + 3;
    
    const s21_size_t size = 5;

    char *s21_destination_copy = s21_memmove(s21_destination, s21_source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);


}
END_TEST

START_TEST(s21_memmove_test9)
{
#line 141
    char s21_destination[] = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};
    char destination[] = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};
    
    char *s21_source = s21_destination + 2;    
    char *source = destination + 2;
    
    const s21_size_t size = 5;

    char *s21_destination_copy = s21_memmove(s21_destination, s21_source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);


}
END_TEST

START_TEST(s21_memmove_test10)
{
#line 157
    char s21_destination[] = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};
    char destination[]     = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};
    
    char *s21_source = s21_destination + 3;    
    char *source = destination + 3;
    
    const s21_size_t size = 5;

    char *s21_destination_copy = s21_memmove(s21_destination, s21_source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);


// TESTS WITHOUT OVERLAPPING SOURCE AND DESTINATION

}
END_TEST

START_TEST(s21_memmove_test11)
{
#line 175
    char s21_source[] = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};
    char source[]     = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};
    
    char *s21_destination = s21_source + 3;    
    char *destination = source + 3;
    
    const s21_size_t size = 2;

    char *s21_destination_copy = s21_memmove(s21_destination, s21_source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);


}
END_TEST

START_TEST(s21_memmove_test12)
{
#line 191
    char s21_source[] = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};
    char source[] = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};
    
    char *s21_destination = s21_source + 3;    
    char *destination = source + 3;
    
    const s21_size_t size = 3;

    char *s21_destination_copy = s21_memmove(s21_destination, s21_source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);


}
END_TEST

START_TEST(s21_memmove_test13)
{
#line 207
    char s21_destination[] = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};
    char destination[] = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};
    
    char *s21_source = s21_destination + 3;    
    char *source = destination + 3;
    
    const s21_size_t size = 2;

    char *s21_destination_copy = s21_memmove(s21_destination, s21_source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);


}
END_TEST

START_TEST(s21_memmove_test14)
{
#line 223
    char s21_destination[] = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};
    char destination[] = { 'H', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'w', '!', '\0'};

    char *s21_source = s21_destination + 3;    
    char *source = destination + 3;

    const s21_size_t size = 3;

    char *s21_destination_copy = s21_memmove(s21_destination, s21_source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);


}
END_TEST

START_TEST(s21_memmove_test15)
{
#line 239
    char s21_destination[] = { 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', '\0' };
    char destination[]     = { 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', '\0' };
    
    char *s21_source = s21_destination + 2;    
    char *source = destination + 2;
    
    const s21_size_t size = 5;

    char *s21_destination_copy = s21_memmove(s21_destination, s21_source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);


}
END_TEST

START_TEST(s21_memmove_test16)
{
#line 255
    char s21_destination[] = { 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', '\0' };
    char destination[]     = { 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', '\0' };
    
    char *s21_source = s21_destination + 3;    
    char *source = destination + 3;
    
    const s21_size_t size = 5;

    char *s21_destination_copy = s21_memmove(s21_destination, s21_source, size);
    char *destination_copy = memmove(destination, source, size);

    ck_assert_mem_eq(s21_destination, destination, size);
    ck_assert_mem_eq(s21_destination_copy, destination_copy, size);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_memmove_test1);
    tcase_add_test(tc1_1, s21_memmove_test2);
    tcase_add_test(tc1_1, s21_memmove_test3);
    tcase_add_test(tc1_1, s21_memmove_test4);
    tcase_add_test(tc1_1, s21_memmove_test5);
    tcase_add_test(tc1_1, s21_memmove_test6);
    tcase_add_test(tc1_1, s21_memmove_test7);
    tcase_add_test(tc1_1, s21_memmove_test8);
    tcase_add_test(tc1_1, s21_memmove_test9);
    tcase_add_test(tc1_1, s21_memmove_test10);
    tcase_add_test(tc1_1, s21_memmove_test11);
    tcase_add_test(tc1_1, s21_memmove_test12);
    tcase_add_test(tc1_1, s21_memmove_test13);
    tcase_add_test(tc1_1, s21_memmove_test14);
    tcase_add_test(tc1_1, s21_memmove_test15);
    tcase_add_test(tc1_1, s21_memmove_test16);

    srunner_set_fork_status(sr, CK_NOFORK); srunner_set_fork_status(sr, CK_NOFORK); srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
