#!/bin/bash

# Check the existance of the variables
if [ ! -z "$2" ]
then
	echo "There can be only one path to a folder"
	exit 1
fi

if [ -z "$1" ]
then
	echo "The script cannot be run without any path specified"
	echo "At least one path is neccessary"
	exit 1
fi

# Check if the folder exists
if [ !  -d "$1" ]
then
	echo "The specified directory doesn't exist"
	echo "Please note that the directory should be entered in the following way:"
	echo "/path/to/dir/"
	exit 1
fi

# Check if the path ends with "/"
last_character=${1: -1}
if [ "$last_character" != "/" ]
then
	echo "The specified path should end in '/'"
	exit 1
fi
