#!/bin/bash

# The total number of folders, including the subfolders
num_folders=$(find $1 -type d | wc -l)
echo "Total number of folders (including all nested ones) = $num_folders"

# Top 5 folders with largest size in descending order (path and size)
echo "TOP 5 folders of maximum size arranged in descending order (path and size):"
du -h $1 | sort -n -r | head  -n 5 | awk 'BEGIN{i=1}{printf "%d - %s, %s\n", i, $2, $1, i++}'

# Total number of files
num_files=$(find $1 -type f | wc -l)
echo "Total number of files = $num_files"

# Number of configuration files (.conf)
echo "Number of:"
num_conf=$(find $1 -type f -name "*.conf" | wc -l)
echo "Configuration files (with the .conf extension) = $num_conf"

# Number of executable files
num_exec=$(find $1 -type f -executable | wc -l)
echo "Executable files = $num_exec"

# Log files
num_logs=$(find $1 -type f -name "*.log" | wc -l)
echo "Log files (with the extension .log) = $num_logs"

# Archive files
num_archives=$(find $1 -type f -name "*.zip" -o -name "*.rar" -o -name ".7z" -o -name "*.tar" | wc -l)
echo "Archive files = $num_archives"

# Symbolic links
num_sym_links=$(find $1 -type l | wc -l)
echo "Symbolic links = $num_sym_links"

# Top 10 files with the largest size in descending order (path, size and type)
echo "TOP 10 files of maximum size arranged in descending order (path, size and type:"
for index in {1..10}
do
	file_max=$(find $1 -type f -exec du -h {} + | sort -rh | head -10 | sed "${index}q;d")
	if ! [[ -z $file_max ]]
	then
		echo -n "$index - "
		echo -n "$(echo $file_max | awk '{print $2}'), "
		echo -n "$(echo $file_max | awk '{print $1}'), "
		echo "$(echo $file_max | grep -m 1 -o -E "\.[^/.]+$" | awk -F . '{print $2}')"
	else
		echo "No files found"
	fi
done

# Top 10 executable files with the largest size in descending order (path, size and hash)
echo "TOP 10 executable files of the maximum size arranged in descending order (path, size and MD5 hash of file)"
for index in {1..10}
do
	exe_file_max=$(find $1 -type f -executable -exec du -h {} + | sort -rh | head -10 | sed "${index}q;d")
	if ! [[ -z $exe_file_max ]]
	then
		echo -n "$index - "
		echo -n "$(echo $exe_file_max | awk '{print $2}'), "
		echo -n "$(echo $exe_file_max | awk '{print $1}'), "

		path_exe_file_max=$(echo $exe_file_max | awk '{print $2}')
		MD5_exe_file_max=$(md5sum $path_exe_file_max | awk '{print $1}')
		echo "$MD5_exe_file_max"
	else
		echo "No executables found"
	fi
done
