#!/bin/bash

# The total number of folders, including the subfolders
num_folders=$(find $1 -type d | wc -l)
echo "Total number of folders (including all nested ones) = $num_folders"

# Top 5 folders with largest size in descending order (path and size)
echo "TOP 5 folders of maximum size arranged in descending order (path and size):"
du -h $1 | sort -n -r | head  -n 5 | awk 'BEGIN{i=1}{printf "%d - %s, %s\n", i, $2, $1, i++}'

# Total number of files
num_files=$(find $1 -type f | wc -l)
echo "Total number of files = $num_files"

# Number of configuration files (.conf)
echo "Number of:"
num_conf=$(find $1 -type f -name "*.conf" | wc -l)
echo "Configuration files (with the .conf extension) = $num_conf"

# Number of executable files
num_exec=$(find $1 -type f -executable | wc -l)
echo "Executable files = $num_exec"

# Log files
num_logs=$(find $1 -type f -name "*.log" | wc -l)
echo "Log files (with the extension .log) = $num_logs"

# Archive files
num_archives=$(find $1 -type f -name "*.zip" -o -name "*.rar" -o -name ".7z" -o -name "*.tar" | wc -l)
echo "Archive files = $num_archives"

# Symbolic links
num_sym_links=$(find $1 -type l | wc -l)
echo "Symbolic links = $num_sym_links"


