#!/bin/bash

# If there are more parameters than 4 or one of the four parameters don't exist
if [ ! -z "$5" ] || [ -z "$column1_background" ] || [ -z "$column1_font_color" ] || [ -z "$column2_background" ] || [ -z "$column2_font_color" ]
then 
	echo "There should be only 4 colors. No more, no less"
	exit 1
fi

if [ $f1_result = $bg1_result ] || [ $f2_result = $bg2_result ]
then
	echo "Font color can't be the same as the background color - you won't be able to read text"
	echo "Also font color should be only a number"
	echo "Please run the script again"
	exit 1
fi

if [ $f1_result = 0 ] || [ $f2_result = 0 ] || [ $bg1_result = 0 ] || [ $bg2_result = 0 ]
then
	echo "Values of color should be in range of 1-6"
	echo "Where 1 - white, 2 - ted, 3 - green, 4 - blue, 5 - purple, 5 - black"
	exit 1
fi
