#!/bin/bash

white_font='\033[0;37;'
white_bg='47m'
red_font='\033[0;31;'
red_bg='41m'
green_font='\033[0;32;'
green_bg='42m'
blue_font='\033[0;34;'
blue_bg='44m'
purple_font='\033[0;35;'
purple_bg='45m'
black_font='\033[0;30;'
black_bg='40m'

bg1_result=0
f1_result=0
bg2_result=0
f2_result=0

bg1_is_default=2
f1_is_default=2
bg2_is_default=2
f2_is_default=2

if [ -z "$column1_background" ]
then
	column1_background=1
	bg1_is_default=1
fi

if [ -z "$column1_font_color" ]
then
	column1_font_color=6
	f1_is_default=1
fi


if [ -z "$column2_background" ]
then
	column2_background=2
	bg2_is_default=1
fi

if [ -z "$column2_font_color" ]
then
	column2_font_color=6
	f2_is_default=1
fi
case $column1_background in
	1)
		bg1=$white_bg
		bg1_result=1
		bg1_text="white"
		;;
	2)
		bg1=$red_bg
		bg1_result=2
		bg1_text="red"
		;;
	3)
		bg1=$green_bg
		bg1_result=3
		bg1_text="green"
		;;
	4)
		bg1=$blue_bg
		bg1_result=4
		bg1_text="blue"
		;;
	5)
		bg1=$purple_bg
		bg1_result=5
		bg1_text="purple"
		;;
	6)
		bg1=$black_bg
		bg1_result=6
		bg1_text="black"
		;;
esac

case $column1_font_color in
	1)
		f1=$white_font
		f1_result=1
		f1_text="white"
		;;
	2)
		f1=$red_font
		f1_result=2
		f1_text="red"
			;;
	3)
		f1=$green_font
		f1_result=3
		f1_text="green"
		;;
	4)
		f1=$blue_font
		f1_result=4
		f1_text="blue"
		;;
	5)
		f1=$purple_font
		f1_result=5
		f1_text="purple"
		;;
	6)
		f1=$black_font
		f1_result=6
		f1_text="black"
		;;
esac	
	
case $column2_background in
	1)
		bg2=$white_bg
		bg2_result=1
		bg2_text="white"
		;;
	2)
		bg2=$red_bg
		bg2_result=2
		bg2_text="red"
		;;
	3)
		bg2=$green_bg
		bg2_result=3
		bg2_text="green"
		;;
	4)
		bg2=$blue_bg
		bg2_result=4
		bg2_text="blue"
		;;
	5)
		bg2=$purple_bg
		bg2_result=5
		bg2_text="purple"
		;;
	6)
		bg2=$black_bg
		bg2_result=6
		bg2_text="black"
		;;
esac
		
case $column2_font_color in
	1)
		f2=$white_font
		f2_result=1
		f2_text="white"
		;;
	2)
		f2=$red_font
		f2_result=2
		f2_text="red"
		;;
	3)
		f2=$green_font
		f2_result=3
		f2_text="green"
		;;
	4)
		f2=$blue_font
		f2_result=4
		f2_text="blue"
		;;
	5)
		f2=$purple_font
		f2_result=5
		f2_text="purple"
		;;
	6)
		f2=$black_font
		f2_result=6
		f2_text="black"
		;;
esac
